### ISSUE TITLE
xrange not defined in main.py

### ISSUE THREAD

**Issue by srushti93** [Pranshu258/Image_Completion#1]
I am missing something in the code? Would appreciate your help on this. Thanks!

[capture](https://user-images.githubusercontent.com/43801646/53841662-5b75ad00-3f6b-11e9-9070-9763ce5fac45.PNG)

**Comment by Pranshu258** [comment]
I guess you are using Python 3, "xrange" function is not available in Python 3.
Our code was written in Python 2, however, it should work if you replace "xrange" with "range".
Hope this helps

**Comment by srushti93** [comment]
I downgraded my python to 2.7.4. But now I am getting this error:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import energy
  File "/Users/jt6w/Desktop/Image_Completion-master/energy.py", line 4, in <module>
    import cv2, numpy as np, sys, math, operator, maxflow, random, config as cfg
  File "/Users/jt6w/anaconda3/lib/python2.7/site-packages/maxflow/__init__.py", line 37, in <module>
    from . import _maxflow
ImportError: dlopen(/Users/jt6w/anaconda3/lib/python2.7/site-packages/maxflow/_maxflow.so, 2): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE
  Referenced from: /Users/jt6w/anaconda3/lib/python2.7/site-packages/maxflow/_maxflow.so
  Expected in: dynamic lookup

I think this is a mac issue but I am not sure how can I resolve it. Any suggestions?  

Thanks

**Comment by Pranshu258** [comment]
This is a known problem with PyMaxFlow on Mac, please go through the link given below, it should solve this issue. 
https://github.com/pmneila/PyMaxflow/issues/13
