### ISSUE TITLE
Incorrect licensing: must be licensed under GPL v3

### ISSUE THREAD

**Issue by wlinna** [Pranshu258/Image_Completion#2]
This software uses PyMaxFlow library, which is GPL 3.0 -licensed. The conditions of GPL license require, that if GPL-licensed library is used, the work as a whole must be distributed under GPL as well.

https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL

Please change the license to GPL 3.

**Comment by Pranshu258** [comment]
Updated the license to GNU GPL v3
